const Cardsdata = [
  {
    id: 1,
    title: "MongoDB in Action, 2nd Edition",
    subtitle: "Covers MongoDB version 3.0",
    imgdata: "https://itbook.store/img/books/9781617291609.png",
    somedata: " 6525 + order placed from here recently",
    url: "https://itbook.store/books/9781617291609",
    price: 350,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 2,
    title: "MongoDB and Python",
    subtitle:
      "Patterns and processes for the popular document-oriented database",
    imgdata: "https://itbook.store/img/books/9781449310370.png",
    somedata: " 2525 + order placed from here recently",
    url: "https://itbook.store/books/9781449310370",
    price: 2500,
    rating: "3.9",
    qnty: 0,
  },
  {
    id: 3,
    title: "Building Node Applications with MongoDB and Backbone",
    subtitle: "Rapid Prototyping and Scalable Deployment",
    imgdata: "https://itbook.store/img/books/9781449337391.png",
    somedata: " 650 + order placed from here recently",
    url: "https://itbook.store/books/9781449337391",
    price: 700,
    rating: "4.2",
    qnty: 0,
  },
  {
    id: 4,
    title: "Practical MongoDB",
    subtitle: "Architecting, Developing, and Administering MongoDB",
    imgdata: "https://itbook.store/img/books/9781484206485.png",
    somedata: " 300 + order placed from here recently",
    url: "https://itbook.store/books/9781484206485",
    price: 70,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 5,
    title: "The Definitive Guide to MongoDB, 3rd Edition",
    subtitle: "A complete guide to dealing with Big Data using MongoDB",
    imgdata: "https://itbook.store/img/books/9781484211830.png",
    somedata: "1050 + order placed from here recently",
    url: "https://itbook.store/books/9781484211830",
    price: 2100,
    rating: "4.0",
    qnty: 0,
  },
  {
    id: 6,
    title: "MongoDB Performance Tuning",
    subtitle: "Optimizing MongoDB Databases and their Applications",
    imgdata: "https://itbook.store/img/books/9781484268780.png",
    somedata: " 1100 + order placed from here recently",
    url: "https://itbook.store/books/9781484268780",
    price: 1000,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 7,
    title: "Pentaho Analytics for MongoDB",
    subtitle:
      "Combine Pentaho Analytics and MongoDB to create powerful analysis and reporting solutions",
    imgdata: "https://itbook.store/img/books/9781782168355.png",
    somedata: "500 + order placed from here recently",
    url: "https://itbook.store/books/9781782168355",
    price: 300,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 8,
    title: "Pentaho Analytics for MongoDB Cookbook",
    subtitle:
      "Over 50 recipes to learn how to use Pentaho Analytics and MongoDB to create powerful analysis and reporting solutions",
    imgdata:
      "https://static.packt-cdn.com/products/9781783553273/cover/smaller",
    somedata: "500 + order placed from here recently",
    url: "https://itbook.store/books/9781783553273",
    price: 1600,
    rating: "3.2",
    qnty: 0,
  },
  {
    id: 9,
    title: "Web Development with MongoDB and NodeJS, 2nd Edition",
    subtitle:
      "Build an interactive and full-featured web application from scratch using Node.js and MongoDB",
    imgdata: "https://itbook.store/img/books/9781785287527.png",
    somedata: "2525 + order placed from here recently",
    url: "https://itbook.store/books/9781785287527",
    price: 1200,
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 10,
    title: "MongoDB Cookbook, 2nd Edition",
    subtitle:
      "Harness the latest features of MongoDB 3 with this collection of 80 recipes - from managing cloud platforms to app development, this book is a vital resource",
    imgdata: "https://itbook.store/img/books/9781785289989.png",
    somedata: "3425 + order placed from here recently",
    url: "https://itbook.store/books/9781785289989",
    price: 500,
    rating: "4.1",
    qnty: 0,
  },
];

export default Cardsdata;